# version: "3.3"

services:
  web:
    build: .
    ports:
      - 8501:8501

    # volumes:
    #   - .:/app

    networks:
      - scrapenet

  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - scrapevol:/ollama
    networks:
      - scrapenet
    # deploy:
    #   resources:
    #     limits:
    #       memory: 6G
    entrypoint: ["/usr/bin/bash","/pull-llama3.sh"]


networks:
  scrapenet:
    driver: bridge

volumes:
  scrapevol:
    driver: local
